abstract: Perl extension for writing XML
author: Mark Lawrence <nomad@null.net>
build_requires: 
  Test::Exception: 0
  Test::Memory::Cycle: 0
  Test::More: 0.42
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: GPL
name: XML-API
no_index: 
  directory: 
    - inc
    - t
requires: 
  XML::SAX: 0
version: 0.17
